### PR TITLE
type annotations and using pathlib

### PR DESCRIPTION
**Pull request by fchapoton**
This is adding many typing annotations, and also using the `pathlib` library. This needs to be **tested** by serious users before merging.

### CODE REVIEW

**Comment by mantepse** [comment]
I'll test it for a while, say a week or so.  Are there any user-visible changes?

**Comment by fchapoton** [comment]
nein, ich denke nicht

**Comment by fchapoton** [comment]
so, is it working as expected ?

**Review by mantepse — APPROVED** [review]
works for me!

**Pull request merged**
