### PR TITLE
Fix typeset output

### PR DESCRIPTION
**Pull request by EmmanuelCharpentier**
- Reintegrate Alessandro Presta's @apresta  fix to typesetting, somehow dropped.
- [ Cosmetic ] Reformatted docstring >80 characters wide.

Please review this before I merge it.

### CODE REVIEW

**Comment by hivert** [comment]
I tried to use this one instead of the elpa one. I got the following error message:

```
error in process filter: sage-shell-view-latex-str: Symbol’s value as variable is void: sage-shell-view-latex-math-environment
error in process filter: Symbol’s value as variable is void: sage-shell-view-latex-math-environment
```

But perhaps this is due to some customization on my side...

**Comment by EmmanuelCharpentier** [comment]
Thanks for thé report. I'll look up that tomorrow.Le 11 juin 2023 22:12, Florent Hivert ***@***.***> a écrit :
I tried to use this one instead of the elpa one. I got the following error message:
error in process filter: sage-shell-view-latex-str: Symbol’s value as variable is void: sage-shell-view-latex-math-environment
error in process filter: Symbol’s value as variable is void: sage-shell-view-latex-math-environment

But perhaps this is due to some customization on my side...

**Comment by dimpase** [comment]
@apresta

**Comment by EmmanuelCharpentier** [comment]
WorksForMe(TM)...

> I tried to use this one instead of the elpa one. I got the following error message:

How did you proceed ?

> But perhaps this is due to some customization on my side...

Could you check this again ?

**Comment by EmmanuelCharpentier** [comment]
BTW : `C-h v sage-shell-view-latex-math-environment` gives me : 

```
sage-shell-view-latex-math-environment is a variable defined in ‘sage-shell-view.el’.

Its value is "math"

Math environment for LaTeX.

  You can customize this variable.
```

Could you look up this variable in *your*  `sage-shell-view.el` ?

In the proposed version (visible in Github in the "Reintegrate..." patcc) , I see : 

```
(defcustom sage-shell-view-latex-math-environment "math"
  "Math environment for LaTeX."
  :group 'sage-shell-view
  :type 'string)
```

at lines 174-177 of `sage-shell-view.el`. If you don't see it, you may have a botched merge.

Keep me posted.

**Comment by hivert** [comment]
Cloning 
```f394754ebca227d1959f991069ab86a613350b6d```
works ! It seems that your last merge went wrong.

**Comment by dimpase** [comment]
the standard way to fetch the branch of a PR number 42  in a repo foo would be to
```
git fetch foo pulls/42/head
```
No need to get stuff from the repo of the creator of the PR.

**Comment by EmmanuelCharpentier** [comment]
I do not understand the origin of the third commit : I do not remember doing it. Top of my log : 

```
charpent@zen-book-flip:~/Dev/sage-shell-mode$ git log | head n=20
head: impossible d'ouvrir 'n=20' en lecture: Aucun fichier ou dossier de ce type
charpent@zen-book-flip:~/Dev/sage-shell-mode$ git log | head 
commit f394754ebca227d1959f991069ab86a613350b6d
Author: Emmanuel Charpentier <emm.charpentier@free.fr>
Date:   Sat Jun 10 10:27:15 2023 +0200

    Reintegrate Alessandro Presta's fix to typesetting, somehow dropped.
    
    [ Cosmetic ] Reformatted docstring >80 characters wide.

commit 237aae32a944f31ff2d1cf712a26136c18794c68
Author: Emmanuel Charpentier <emm.charpentier@free.fr>
charpent@zen-book-flip:~/Dev/sage-shell-mode$ man head
charpent@zen-book-flip:~/Dev/sage-shell-mode$ git log | head -n 20
commit f394754ebca227d1959f991069ab86a613350b6d
Author: Emmanuel Charpentier <emm.charpentier@free.fr>
Date:   Sat Jun 10 10:27:15 2023 +0200

    Reintegrate Alessandro Presta's fix to typesetting, somehow dropped.
    
    [ Cosmetic ] Reformatted docstring >80 characters wide.

commit 237aae32a944f31ff2d1cf712a26136c18794c68
Author: Emmanuel Charpentier <emm.charpentier@free.fr>
Date:   Sun Apr 9 20:34:09 2023 +0200

    Re-enable typeset output in Emacs' *Sage* buffer.
    
    This patch adapts sage-shell-mode to recent pmodification of Sages' rich output
    generation, and filters spurious math delimiters.

commit 80fbb4ee9ed8507d22214ed7a4ffd135c9e8c7c8
Author: Frédéric Chapoton <chapoton@unistra.fr>
Date:   Thu Oct 20 12:12:51 2022 +0200
```

Worse : I do not know how to get rid of this "commit from Mars'. Time to crack Github's documentation... tomorrow !

**Comment by EmmanuelCharpentier** [comment]
> it's just git: on your machine do
> 
> ```
> git revert <commit>
> ```
That wasn't necessary, since the "commit from Mars" doesn't exist on my machine.
> ```
> git push -f
> ```

That did it. Thank you, Dima !
 Florent (and others ?) : a final check before I merge ?

**Comment by EmmanuelCharpentier** [comment]
Re-checked, merged, tested.

Done...

**Comment by EmmanuelCharpentier** [comment]
> The change to the function `supported_output` in the file `emacs_sage_shell_view.py` from commit [658dced](https://github.com/sagemath/sage-shell-mode/commit/658dcedccf2c1a45c6d8d8887f8d992d2977f14a) looks wrong.

What is wrong ?

Would you mind  open another issue and explain what seems wring and why ?

Sincerely,

**Pull request merged**
