### PR TITLE
Fix latex rendering in sage-shell-view

### PR DESCRIPTION
**Pull request by apresta**
This fixes issue #61.
Adapted from PR #70 with @aikrahguzar's help.

### CODE REVIEW

**Comment by EmmanuelCharpentier** [comment]
That's a better alternative than #72. However, it requires some documentation, and a default (initial) value.

I retracted (closed) #72.

Thanks !

**Comment by apresta** [comment]
@EmmanuelCharpentier sounds good, thanks.
Can you please clarify what needs documenting and an initial value?

**Comment by EmmanuelCharpentier** [comment]
> Can you please clarify what needs documenting and an initial value?

- Document why this variable may be useful and what is its default value
- Possibly give an example of customization (I have trouble thinking one...).

HTH,

**Comment by apresta** [comment]
This PR doesn't introduce any new variable, it actually deletes `sage-shell-view-latex-math-environment` which is no longer needed.

**Comment by hivert** [comment]
Thanks a lot for this work ! Any show stopper merging this one ? Having to type "view(...)" each time and switching to my browser seriously disrupt my workflow.

**Comment by apresta** [comment]
> Thanks a lot for this work ! Any show stopper merging this one ? Having to type "view(...)" each time and switching to my browser seriously disrupt my workflow.

No show stoppers, this is ready to go.

**Comment by dimpase** [comment]
@EmmanuelCharpentier - I've promoted you to a maintainer of this repo, you can merge things now.

**Comment by hivert** [comment]
> @hivert - I can promote you to maintainer of this repo too - would you like to be one?

First of all, thank for the proposition !

If I'd definitely like to help, I'm still at the script-kiddie level concerning emacs internals and lisp programming. I don't think I'm knowledgeable enough for the task. Sorry...

**Comment by dimpase** [comment]
@hivert - well, I suppose you can test things, and that's good enough. Of course I can merge this without looking (I haven't been using emacs for 20 years), but that's not as good.

**Comment by EmmanuelCharpentier** [comment]
> @EmmanuelCharpentier - I've promoted you to a maintainer of this repo, you can merge things now.

Thanks ! I'll do that (I've reviewed this patch already, and I'm using it currently).

**Comment by EmmanuelCharpentier** [comment]
I just accepted the merge. It *should* appear on Melpa in a not too long time. Bug me if that doesn't happen.

**Comment by EmmanuelCharpentier** [comment]
Well...
- This PR *did* reach MELPA.
- The resulting package : 
    + *does* plot in the Sage buffer, but
    + dos *not* typeset LaTeX.
whereas my local branch does. I'll investigate.

**Comment by EmmanuelCharpentier** [comment]
Could you please review [this pull request](https://github.com/sagemath/sage-shell-mode/pulls) which reintegrates @apresta 's fix, which somehow disappeared from  the previous pull request I merged (after successfully reviewing its branch) ?

Thanks again...

**Pull request merged**
